name: notes_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  cloud_firestore: 5.0.1
  firebase_core: 3.1.0
  sqflite: ^2.3.3+1
  flutter: 
    sdk: flutter
  path: ^1.9.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

